// PRODUCT CART ACTION TYPES
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const PRODUCT_LOADED = "PRODUCT_LOADED";

// PRODUCT ACTION TYPES
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT= 'DELETE_PRODUCT'


// PRODUCT filter action types
export const TOGGLE_BRAND = "TOGGLE_BRAND";
export const TOGGLE_STOCK = "TOGGLE_STOCK";



